before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/grimoire
    binary: grimoire
    ldflags:
      - -s -w -X main.version={{.Version}}

brews:
  - name: grimoire
    homepage: https://github.com/gphorvath/grimoire
    description: A prompt engineer's Grimoire to assist with getting the best results from Generative AI prompts
    license: MIT
    test: |
      system "#{bin}/grimoire --version"
    install: |
      bin.install "grimoire"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    repository:
      owner: gphorvath
      name: grimoire
      branch: main
      pull_request:
        enabled: true
        base:
          branch: main

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: https://github.com/gphorvath/grimoire
    description: A prompt engineer's Grimoire to assist with getting the best results from Generative AI prompts
    maintainer: Gregory Horvath
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - git

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'